### ISSUE TITLE
No reason set for skipped works in ORCID importer

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#723]
While importing the ORCID dump:
```
2019-04-15 11:32:00 INFO dissemin.papers.orcid:138  https://pub.orcid.org/v2.1/0000-0002-9005-9502/works
2019-04-15 11:32:01 INFO dissemin.papers.orcid:138  https://pub.orcid.org/v2.1/0000-0002-9005-9502/works/5101707,5101717,5101709,5101713,5101712,5101711,5101714,5101716,5101715,5101706,5101708,5101710
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/dissemin/prod/ingest_orcid.py", line 13, in <module>
    o.bulk_import('/home/pintoch/summaries')
  File "/home/dissemin/prod/backend/orcid.py", line 287, in bulk_import
  File "/home/dissemin/prod/backend/orcid.py", line 220, in fetch_orcid_records
    continue
AttributeError: 'OrcidWork' object has no attribute 'reason'
```

**Comment by Phyks** [comment]
I think the issue is coming from this `logging` line: https://github.com/dissemin/dissemin/blob/master/backend/orcid.py#L217

as `OrcidWork` only has a `skip_reason` attribute and no `reason` attribute: https://github.com/dissemin/dissemin/blob/master/papers/orcid.py#L322-L330.

Is it safe to start it again on Tulpan to check this is indeed coming from this? What should be the command line?

I tried to copy part of the ORCID dump locally and run `python ingest_orcid.py` directly, but I probably missed something as I get only "Invalid profile" errors.

**Comment by wetneb** [comment]
@Phyks sure, feel free to start it again. The error only occurs after a while, but I assume this should be reproducible with the "0000-0002-9005-9502" profile only (so it can probably be debugged without the dump at all).

**Comment by Phyks** [comment]
Everything is working fine locally, I'm not sure "0000-0002-9005-9502" was at fault.

I replicated the small changes on tulpan and let the `ingest_orcid` run in a screen session under my username. I'll let you know.
