### ISSUE TITLE
Make Crossref ingestion more robust

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#759]
Currently, running `CrossRefAPI().fetch_and_save_new_records()` gives:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/dissemin/prod/backend/crossref.py", line 564, in fetch_and_save_new_records
    p.update_index()
  File "/home/dissemin/prod/papers/models.py", line 1276, in update_index
    index.update_object(self, using=using)
  File "/home/dissemin/prod/.venv/lib/python3.5/site-packages/haystack/indexes.py", line 284, in update_object
    backend.update(self, [instance])
  File "/home/dissemin/prod/.venv/lib/python3.5/site-packages/haystack/backends/elasticsearch_backend.py", line 193, in update
    self.conn.indices.refresh(index=self.index_name)
  File "/home/dissemin/prod/.venv/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/dissemin/prod/.venv/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 40, in refresh
    '_refresh'), params=params)
  File "/home/dissemin/prod/.venv/lib/python3.5/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout) 
  File "/home/dissemin/prod/.venv/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 180, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='diego.dissem.in', port=8080): Read timed out. (read timeout=10))
```

**Comment by beckstefan** [comment]
Since #855, this does no longer apply.
